def employee():
    employeedetails=[
        {
            "id":1,
            "name":"emp1",
            "mobile":1111111111,
            "mail":"abcd@comp.com"
        },
        {
            "id":2,
            "name":"emp2",
            "mobile":2222222222,
            "mail":"abcd2@comp.com"
        },
        {
            "id":3,
            "name":"emp3",
            "mobile":3333333333,
            "mail":"abcd3@comp.com"
        },
        {
            "id":4,
            "name":"emp4",
            "mobile":4444444444,
            "mail":"abcd4@comp.com"
        },
        {
            "id":5,
            "name":"emp5",
            "mobile":5555555555,
            "mail":"abcd5@comp.com"
        },
    ]
    return employeedetails